### ISSUE TITLE
Strange paging behavior 2

### ISSUE THREAD

**Issue by schrolf** [mami-project/pto3-go#109]
Hi

I don't get the 'prev' link on result page 1. Tested on query 'c89137bfcaf7e2f7daaccf4e2eeb0f458f851eec015044dc0cd03273087c8a83' and '4df0ec4e7648be28f5c812826992b782baae620c365f193f4ad3a4670ec056c1'.

Rolf

**Comment by britram** [comment]
this is working as designed. there should be no prev link on the first page of a result, and there should be no next link on the last page of a result.

**Comment by schrolf** [comment]
I assume page 0 to be the first page. So page 1 should have prev link to page 0.

**Comment by britram** [comment]
ack, will look into this

**Comment by britram** [comment]
Oops. Assumed the first page was zero in the first half of the function and one in the second half. Fixed.
