### ISSUE TITLE
Mmap not building on Windows

### ISSUE THREAD

**Issue by schrolf** [mami-project/pto3-go#92]
Hi
I just pulled the latest version of the PTO and had the problem, that mmap.go was not building on windows.
Solved it by deleting the file locally before build.
Rolf

**Comment by sten13** [comment]
I have checked in a fix that should prevent mmap.go from building on windows. Please check out in a fresh directory and build again to confirm.

**Comment by schrolf** [comment]
Works like a charm. Thx!
